s1=" Learning "
s2=" Python "
# print(s[0])
# print(s[2:8:1])
# print(s[0:])
# print(s[::1])
# print(s[::-2])
# print(s1+s2)
# print(s1*3)
# print(len(s1))
#print('on' in s2)
# print(s1,s2)
# print(s1.rstrip()+s2.lstrip())
# print(s1.find("python"))
s = "abcabcABFDabcabGFFcbcbcbc"
# print(s.count("bc"))
# s3 = s.replace("a","cb")
# print(s3)
print(s.capitalize())
print(s.title())
print(s.upper())
print(s.swapcase())
print(s.isalpha())
print(s.isnumeric())
print(s.isalnum())